services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: politikoks-netology-grafana
    environment:
      GF_PATH_CONFIG: /etc/grafana/grafana.ini
    ports:
      - 80:3000
    volumes:
      - './grafana:/etc/grafana'
      - grafana-data:/var/lib/grafana
    networks:
      - politikoks-my-netology-hw
    restart: always
      
volumes:
  grafana-data:

networks:
  politikoks-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
