version: '3'

services:

  pushgateway:
    image: prom/pushgateway:v1.6.2

    container_name: pushgateway
    ports:
      - 9091:9091
    networks:
      - politikoks-my-netology-hw

    depends_on:
      - prometheus
    
    restart: unless-stopped
